routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



####################################
#
#
# Security Routes like login - logout - Registration etc 
#
#
####################################




####################################
#
#
# Front End Routes that shows customer how beautiful are we  -_-
#
#
####################################



Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [   'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' , 'localize' ]
    ],
    function()
    {

        Route::get('login' , function(){

           if (Auth::check()) {
                 return view('backend.dashboard.index');
           }else{
                return view('auth.login');
           }
        }); 

        Route::post('authenticate' , 'Auth\LoginController@authenticate');

        Route::post('logout' , 'Auth\LoginController@logout') ;
       
        Route::get('/','frontend\HomeController@getHomePage')->name('home_page');
        Route::get('/categories' , 'frontend\CategoriesController@index'); 



       
        Route::get('/special-occassion/{id}/{name}','frontend\SpeacialEventController@index');

        Route::get('contact','frontend\ContactUsController@contact');
        Route::post('post_contact' , 'frontend\ContactUsController@contactmsg')->name('contactmsg'); 


      
        Route::get('/{id}/sub-categories' , 'frontend\CategoriesController@indexSub');

        Route::get('/{id}/sub-categories/{sub_id}/products' , 'frontend\CategoriesController@indexProducts'); 


        Route::get('/{id}/sub-categories/{sub_id}/products/{product_id}' , 'frontend\CategoriesController@productDetails'); 


        Route::get('careers_list' , 'frontend\CareerController@index');   
        Route::get('/about-us', 'frontend\InformationalController@about' );   

  


     
        
        Route::post('subscribe' , 'frontend\HomeController@subscribe')->name('subscribe');



      
        Route::get('/customer-login', 'CustomerAuth\CustomerAuthController@showLoginForm')->name('customer_login');
        Route::post('/customer-login', 'CustomerAuth\CustomerAuthController@postLogin');


        Route::get('/customer-register' , 'CustomerAuth\CustomerRegistrationController@getRegistrationForm')->name('customer_register'); 
        Route::post('/customer-register' , 'CustomerAuth\CustomerRegistrationController@createAccount')->name('create_account'); 



        Route::get('customer-forget-password' , 'CustomerAuth\CustomerForgetPasswordController@showLinkRequestForm')->name('forgetPassword'); 
        Route::post('post-reset-email' , 'CustomerAuth\CustomerForgetPasswordController@sendResetLinkEmail')->name('sendResetLinkEmail'); 


        Route::get('customer-reset-password/{token}' , 'CustomerAuth\CustomerResetPasswordController@showResetForm'); 
        Route::post('reset-password' , 'CustomerAuth\CustomerResetPasswordController@reset');




        Route::group(['middleware' => ['customer'] , 'prefix'=>'customer' ], function () {
            
            Route::get('/dashboard' , 'frontend\CustomerController@dashboard')->name('customer_dashboard'); 
            Route::get('/account_information/edit' , 'frontend\CustomerController@accountInformation')->name('customer_information'); 
            Route::put('/account_information/{id}/update' , 'frontend\CustomerController@updateAccountInformation')->name('updateAccount'); 

            Route::put('/account_password/{id}/update' , 'frontend\CustomerController@updateAccountPassword')->name('updateAccountPassword');

            Route::get('/check_update_account' , 'frontend\CustomerController@checkUpdate' )->name('check_update');

            Route::post('/logout' , 'CustomerAuth\CustomerAuthController@logout')->name('logout_customer');
            // shopping cart page and logic  -_-    
            Route::get('/shopping-cart' , 'frontend\CustomerController@getCart')->name('shopping_cart'); 
            // whish list logic -_-
            Route::get('/add_product_to_whislist/{id}' , 'frontend\WishListController@addProduct' )->name('addProductToWishlist'); 
            Route::get('/wishlist' , 'frontend\WishListController@index')->name('whislist'); 
            Route::post('/wishlist/delete', 'frontend\WishListController@removeWishlistProduct' )->name('removeWishlistProduct');



            Route::get('checkout' , 'frontend\CheckoutController@getCheckoutBlade')->name('getCheckout'); 


            Route::get('my-orders' , 'frontend\OrderController@getMyOrders')->name('myOrders');
            Route::get('my-orders/{order_ticket}/details' , 'frontend\OrderController@orderDetails'); 
            Route::post('place-order' , 'frontend\OrderController@hackit')->name('order'); 



         
        });




 
        // search mechanism  -_- 
        Route::get('search_result' , 'frontend\SearchController@searchResutlt');
         




    });

 


####################################
#
#
# Backend Routes that describe how we do it  -_- 
#
#
####################################


Route::group(['prefix' => LaravelLocalization::setLocale() , 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' , 'auth' ]], function()
{
 
		Route::get('dashboard' , function(){ 
            return view('backend.dashboard.index');
		})->name('dashboard');
		Route::resource('language', 'Backend\LanguageController');
		Route::resource('user', 'Backend\UserController');
		Route::get('user/profile/{id}', 'Backend\UserController@profile')->name('user.profile');
        Route::resource('messages','Backend\messagesController');
        Route::resource('sayabout','Backend\SayAbout');
        Route::get('/about' , 'Backend\AboutController@index')->name('about') ;
        Route::put('/about/{id}' , 'Backend\AboutController@update')->name('about_update') ;
        Route::get('/about-photos/{related_to}' , 'Backend\AboutController@getImages')->name('about-photos') ;
        Route::delete('/about-photos/{id}', 'Backend\AboutController@destroyImage' )->name('destroy-image');
        Route::resource('dessertdepartment', 'Backend\DessertDepartmentController');
        Route::get('sub-depts/{id}' , 'Backend\DessertDepartmentController@getSubDepts')->name('sub_departments');
        Route::get('add-new-sub/{id}' , 'Backend\DessertDepartmentController@addNewSub')->name('add_new_sub');
        Route::post('post_sub' , 'Backend\DessertDepartmentController@postNewSub')->name('post_sub');
        Route::get('edit_sub/{id}' , 'Backend\DessertDepartmentController@editSubDepartment' )->name('sub_edit') ;
        Route::put('post_sub_update/{id}' , 'Backend\DessertDepartmentController@updateSubDepartment' )->name('update_sub_department');
        Route::delete('sub_department/{id}', 'Backend\DessertDepartmentController@deleteSubDepartment')->name('deleteSubDepartment');
        Route::get('items/{id}' , 'Backend\DessertDepartmentController@getDesertItemList')->name('items');
        Route::get('add-new-item/{id}' , 'Backend\DessertDepartmentController@addNewItem')->name('addNewItem');
        Route::post('post_item' , 'Backend\DessertDepartmentController@postNewItem')->name('postNewItem');
        Route::get('edit_item/{id}' , 'Backend\DessertDepartmentController@editItem' )->name('editItem') ;
        Route::put('update_item/{id}' , 'Backend\DessertDepartmentController@updateItem' )->name('updateItem');
        Route::delete('delete_item/{id}' , 'Backend\DessertDepartmentController@deleteItem' )->name('deleteItem');
        // Route::resource('blogdepartment', 'Backend\BlogDepartmentController');
        // Route::resource('careers', 'Backend\BlogController');
        Route::get('careers', 'Backend\BlogController@careers')->name('careers_backend');
        Route::put('careers_post/{id}', 'Backend\BlogController@careersPost')->name('post_career');
		Route::resource('team', 'Backend\TeamController');
        Route::resource('speacialevent', 'Backend\SpecialEventController');
        Route::resource('eventitem', 'Backend\SpeacialEventItemController');
        // Route::resource('social-media', 'Backend\SocialMediaController');
        Route::resource('say','Backend\SayController');
        Route::resource('visitorsMessages','Backend\visitorsMessagesController');
        Route::get('visitorsMessages/showReply/{id}','Backend\visitorsMessagesController@showReply');
        Route::post('visitorsMessages/reply', 'Backend\visitorsMessagesController@Reply');
        Route::get('newsletter' , 'Backend\NewsLetterController@index')->name('newsletter');
        Route::get('newsletter/send-email/{id}' , 'Backend\NewsLetterController@sendEmail')->name('sendEmail');
        Route::get('newsletter/send-bulck' , 'Backend\NewsLetterController@sendBulckEmail')->name('sendBulckEmail');
        Route::post('post_single_email/{id}' , 'Backend\NewsLetterController@postSingleEmail')->name('postSingleEmail');
        Route::post('post_bulck' , 'Backend\NewsLetterController@postBulck')->name('postBulck');



        Route::resource('customers' , 'Backend\CustomerController'); 
        Route::get('orders' , 'Backend\OrderController@index'); 
        Route::get('order/{order_ticket}/{notification?}/details' , 'Backend\OrderController@adminOrderDetails'); 

   


        // mark notification as read  -_- 
        
        Route::get('notification/{id}' , 'Backend\NotificationController@markAsRead');



        Route::resource('slider', 'Backend\SliderController');


});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\About ; 
use App\AboutDescription ; 
use App\AboutPhotos ; 
use App\Language ; 
use LaravelLocalization ; 
use DB ; 
use Auth ; 
use File ; 


class AboutController extends Controller
{
    
	/**
	 * So here we will check if we have about information 
	 * then we will update it unless create a new one  
	 * cause this is a single blade 
	 * @return [type] [description]
	 */
	public function index(){

		// get authenticated  
		$user = Auth::user(); 

	    $about = About::updateOrCreate([
	    	 
	    	'related_to'=>$user->id 
	    	 
	    ]);

	    $languages = Language::where(['status'=>'1'])->get(); 

	    foreach($languages as $language){

		    $about_description = AboutDescription::updateOrCreate([

		    	'about_id'=>$about->id , 
		    	'language_id'=>$language->id


		    ]);

	    	
	    }
	    



 
	    return view('backend.about.index')->withAbout($about)->withLanguages($languages); 
    }

    public function update(Request $request , $id){


    	 
    	$about = About::find($id);


    	$about->status = $request->status == 'on' ? 'active':'not_active' ; 
    	$about->telephone1 = $request->telephone_one ; 
    	$about->tele = $request->telephone_two ;
    	$about->related_to = Auth::user()->id;


    	$about->timestart  = $request->timestart;
    	$about->timeend  = $request->timeend;

        $about->class_num  = $request->class;

        $about->staff_num  = $request->staff;
        $about->master_num  = $request->master;
        $about->kitchen_num  = $request->ketchen;

        $about->since_year   = $request->Since_year;
        $about->email        = $request->email;
        $about->facebook = $request->facebook;
        $about->twitter = $request->twitter;
        $about->google = $request->google;


    	$about->save(); 





 

				if($request->hasFile('file')){


                    /**
                     * i will not delete the old images  
                     */

                    $images = $request->file('file'); 

                    foreach ($images as $image) {
                       


                            $extension = $image->getClientOriginalExtension();
                            $image_rename = str_random(6). '.' .$image->getClientOriginalExtension(); 

                            $image->move(public_path('uploads/about'), $image_rename) ; 


                            /**
                             * Saving  in in our seperated table  
                             * we will fetch  by eloquent 
                             */

                            $pic = new About();

                            $pic->info_img = $image_rename ;


                            $pic->save() ; 


                    }  

            	}

 


            $descriptions = $about->description ; 


            foreach ($descriptions as $description) {
                
                
                $description->about_id = $about->id ; 
                $description->language_id = $description->language_id ;


                $description->name = $request->input("name_".$description->language->label);  
                $description->description = $request->input("about_description_".$description->language->label);
                $description->about = strip_tags($request->input("about_".$description->language->label));
                $description->address = ($request->input("address_".$description->language->label));


                // saving department content !
                $description->save(); 
            }


             // flashing a success message  
                session()->flash('success' , trans('about.about_info_updated')); 

                
    			return back(); 

    }




    /**
     * Fetch User About Photos  
     * as we know that each user has only one about record on database  
     * @param  [type] $related_to [description]
     * @return [type]             [description]
     */
    public function getImages($related_to){



            // get about info 
            $about = About::where(['related_to'=>$related_to])->first(); 

            // then through it we wikll fetch all related photos 
            $photos = $about->photos ; 




            return view('backend.about.about-photos' , compact('photos')); 
            






    }



    public function destroyImage($id){


        $image = AboutPhotos::find($id); 

        $image_path = public_path().'/uploads/about/'.$image->name;

        File::delete($image_path); 


        $image->delete(); 



         // flashing a success message  
        session()->flash('success' , trans('about.about_image_deleted')); 

        return back(); 





    }



    /**
     * Mke Slugs Urls from title  -- 
     * help in seo performance 
     * @param  [type] $text [description]
     * @return [type]       [description]
     */
     public function slugify($string , $separator = '-')
    {
         

            if (is_null($string)) {
                return "";
            }

            // Remove spaces from the beginning and from the end of the string
            $string = trim($string);

            // Lower case everything
            // using mb_strtolower() function is important for non-Latin UTF-8 string | more info: http://goo.gl/QL2tzK
            $string = mb_strtolower($string, "UTF-8");;

            // Make alphanumeric (removes all other characters)
            // this makes the string safe especially when used as a part of a URL
            // this keeps latin characters and arabic charactrs as well
            $string = preg_replace("/[^a-z0-9_\s-ءاأإآؤئبتثجحخدذرزسشصضطظعغفقكلمنهويةى]#u/", "", $string);

            // Remove multiple dashes or whitespaces
            $string = preg_replace("/[\s-]+/", " ", $string);

            // Convert whitespaces and underscore to the given separator
            $string = preg_replace("/[\s_]/", $separator, $string);

            return $string;

    }



}

app/Http/Controllers/Backend/BlogController.php
<?php

namespace App\Http\Controllers\Backend;

use App\BlogDepartment;
use App\DessertDepartments;
use App\Blog;
use App\BlogDescription;
use  App\Language;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use File ;

class BlogController extends Controller
{
     
    public function careers(){

        // get authenticated  
        $user = Auth::user(); 



        $career = Blog::updateOrCreate([
             
            'addby_id'=>$user->id 
             
        ]);

        $languages = Language::where(['status'=>'1'])->get(); 

        foreach($languages as $language){

            $career_description = BlogDescription::updateOrCreate([

                'blog_id'=>$career->id , 
                'language_id'=>$language->id


            ]);

            
        }
        

        return view('backend.blog.create' , compact('career' , 'languages')) ; 

    }


    public function careersPost(Request $request  , $id){

            $career = Blog::find($id) ; 

            $descriptions = $career->description ; 

            foreach ($descriptions as $description) {
                
                $description->blog_id = $career->id ; 
                $description->language_id = $description->language_id ;

                $description->name = $request->input("name_blog_".$description->language->label);  
                $description->description = $request->input("description_blog_".$description->language->label);


                $description->save(); 
            }



             session()->flash('career_update' , trans('backend.careers_updated')); 

             return back(); 

    }


}

resources/views/backend/slider/create.blade.php
@extends('backend.app')

@section('page_title' , trans('backend.add_slide'))

@section('breadcrumb')


					<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">{{ trans('backend.add_slide') }}</h4> 
                    </div>

                  



@endsection  


@section('styles')
    
      <style>
    
        .form_error{
            
            
            margin-top: -25px;
            margin-bottom: 10px;
            color: #d22e2e;

        }

        .error_border{

                box-shadow: 1px 1px 5px red;
        }

        .form_error small{
            word-break: break-word ; 
        }

  </style>

@endsection



@section('content')
					 

                   <div class="col-md-8 col-sm-12">
                        <div class="white-box">
                            <h3 class=" m-b-0">{{ trans('backend.add_slide') }}</h3>
                            <p class="text-muted m-b-30 font-13"> {{ trans('backend.add_slide_notice') }}</p>
                            {{-- <form class="form-horizontal"> --}}
                                  {!! Form::open(['route'=>'slider.store' , 'id'=>'lang_form_add' , 'class'=>'form-horizontal' , 'files'=>true]) !!}
                                <div class="form-group row">
                                    <label   class="col-sm-3 control-label col-form-label">{{ trans('backend.slider_title') }}</label>
                                    <div class="col-sm-9">
                                        <input type="text" value="{!! old('title') !!}" class="form-control {!! $errors->has("title") ? 'error_border':''  !!}"   name="title">
                                        
                                            @if($errors->has("title"))
                                                <span class="form_error"><small>{{ $errors->first("title") }}</small></span>
                                            @endif
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label   class="col-sm-3 control-label col-form-label">{{ trans('backend.slider_image') }}</label>
                                    <div class="col-sm-9">
                                         <input type="file" id="input-file-now" name="file"  class="dropify" />
                                        @if($errors->has("file"))
                                            <span class="form_error"><small>{{ $errors->first("file") }}</small></span>
                                        @endif
                                    </div>
                                </div>
                                 
                               
                           
                        </div>
                    </div>  


                    <div class="col-md-4 col-sm-12">
                        <div class="white-box">
                            <h3 class="m-b-0">{{ trans('backend.publish_options') }}</h3>
                            <br>

                              <div class="row">
                                <label class="col-sm-6 control-label col-form-label">{{ trans('backend.status') }}</label> 
                                <div class="col-sm-6 ">
                                     <input type="checkbox" class="js-switch" checked="true"  name="status"  data-size="small" data-color="#13dafe" /> 
                                </div>

                                
                            </div>
                            
                            <br>  
                            
                            <div class="form-group m-b-0"> 
                                <button type="submit" class="btn btn-info btn-rounded waves-effect waves-light m-t-10 btn-sm">{{ trans('backend.add_slide') }}</button> 
                            </div>

                                 {!! Form::close() !!}
                        </div>
                    </div> 

@endsection 


 
@section('scripts')

    <!-- For Switch  --> 
    <script>

        jQuery(document).ready(function() {
        // Switchery
        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
        $('.js-switch').each(function() {
            new Switchery($(this)[0], $(this).data());
        });

        }); 

        </script>


        <script type="text/javascript">

                $(".bt-switch input[type='checkbox'], .bt-switch input[type='radio']").bootstrapSwitch();
                var radioswitch = function() {
                    var bt = function() {
                        $(".radio-switch").on("switch-change", function() {
                                $(".radio-switch").bootstrapSwitch("toggleRadioState")
                            }),
                            $(".radio-switch").on("switch-change", function() {
                                $(".radio-switch").bootstrapSwitch("toggleRadioStateAllowUncheck")
                            }),
                            $(".radio-switch").on("switch-change", function() {
                                $(".radio-switch").bootstrapSwitch("toggleRadioStateAllowUncheck", !1)
                            })
                    };
                    return {
                        init: function() {
                            bt()
                        }
                    }
                }();
                $(document).ready(function() {
                    radioswitch.init(); 


                     $('.dropify').dropify({
                            tpl: {
                                wrap:            '<div class="dropify-wrapper"></div>',
                                loader:          '<div class="dropify-loader"></div>',
                                message:         '<div class="dropify-message"><span class="file-icon" /> <p>{{ trans("backend.select_slide_image") }}</p></div>',
                                preview:         '<div class="dropify-preview"><span class="dropify-render"></span><div class="dropify-infos"><div class="dropify-infos-inner"><p class="dropify-infos-message">{{ trans("backend.select_slide_image") }}</p></div></div></div>',
                                filename:        '<p class="dropify-filename"><span class="file-icon"></span> <span class="dropify-filename-inner"></span></p>',
                                clearButton:     '<button type="button" class="dropify-clear">{{ trans("backend.remove") }}</button>',
                                errorLine:       '<p class="dropify-error"></p>',
                                errorsContainer: '<div class="dropify-errors-container"><ul></ul></div>'
                            }
                        });


                });

    </script>


       

@endsection 


 

resources/views/backend/slider/index.blade.php
@extends('backend.app')

@section('page_title' , trans('backend.slider_module'))

@section('breadcrumb')


    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">{{ trans('backend.slider_module') }}</h4>
    </div>





@endsection

@php 
    
    $lang = LaravelLocalization::getCurrentLocale(); 
    $laguage = \App\Language::where(['label'=>$lang])->first(); 
    $language_id = $laguage->id ; 
 
@endphp



@section('content')

    <div class="col-sm-12">
        <div class="white-box">


            <a href="{{ route('slider.create' ) }}" class="btn btn-inverse btn-sm btn-rounded pull-right" style="margin-bottom: 10px; ">{{ trans('backend.add_slide') }}</a>

            <div class="table-responsive">
                <table class="table   table-hover color-table info-table " >
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>{{ trans('backend.slider_title') }}</th>
                      

                        <th>{{ trans('backend.slider_image') }}</th>
                        <th>{{ trans('backend.status') }}</th>




                        <th class="text-nowrap">{{ trans('backend.action') }}</th>

                    </tr>
                    </thead>
                    <tbody>



                    @if($sliders->count())


                        @foreach($sliders as $slide)




                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td> {{ $slide->title }}  </td>

                                 <td>
                             
 
                                    <div class="" id="images">

                                        <div class="col-sm-2">
                                            <a  href="{{ asset("uploads/slider/$slide->image") }}" data-effect="mfp-3d-unfold " data-effect="mfp-zoom-out" class="fresco">
                                                <img style="width: 70px; height:70px;border-radius:50%;" src="{{ asset("uploads/slider/$slide->image") }}" class="img-responsive fresco" />
                                            </a>

                                            <style>
                                                .img-responsive
                                                {
                                                    max-width: none !important;

                                                }
                                            </style>
                                        </div>
                                    </div>

                                </td>

                                
 
                                <td>
                                    @if($slide->status == 'not_active')
                                        <span class="label label-danger">{{ trans('backend.not_active') }}</span>
                                    @else
                                        <span class="label label-success">{{ trans('backend.active') }}</span>
                                    @endif

                                </td>





                                <td class="text-nowrap ">
 

                                     
                                   <a  href="{{ route('slider.edit' , $slide->id) }}" data-toggle="tooltip"
                                        data-original-title="{{ trans('backend.edit') }}">
                                        <i class="fa fa-pencil text-inverse m-r-10"></i> </a>


                                    <a  onclick="$('.dessertdepartment_{{ $slide->id }}').submit();"

                                       data-toggle="tooltip" data-original-title="{{ trans('backend.delete') }}">
                                        <i class="fa fa-close text-danger"></i> </a>



                                    {!! Form::open(['route'=>["slider.destroy" , $slide->id ] ,
                                    'class'=>"dessertdepartment_$slide->id" ]) !!}

                                    {!! method_field('DELETE') !!}



                                    {!! Form::close() !!}

                                </td>

                            </tr>

                        @endforeach
                    @else

                        <tr>
                            <td colspan="7" class="text-center">{{ trans('backend.no_slide_found') }}</td>

                        </tr>

                    @endif

                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection





{{--  --}}